-- MySQL Script generated by MySQL Workbench
-- jue 11 feb 2016 11:04:02 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `CAI` DEFAULT CHARACTER SET utf8 ;
USE `CAI`;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `num_empleado` INT(7) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(50) NULL,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`num_empleado`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teacher` (
  `teacher` INT(7) NOT NULL,
  INDEX `fk_teacher_usuario_idx` (`teacher` ASC),
  PRIMARY KEY (`teacher`),
  CONSTRAINT `fk_teacher_usuario`
    FOREIGN KEY (`teacher`)
    REFERENCES `usuario` (`num_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo` (
  `codigo` VARCHAR(7) NOT NULL,
  `nivel` INT(1) NOT NULL,
  `teacher` INT(7) NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_grupo_teacher1_idx` (`teacher` ASC),
  CONSTRAINT `fk_grupo_teacher1`
    FOREIGN KEY (`teacher`)
    REFERENCES `teacher` (`teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carrera` (
  `siglas` VARCHAR(7) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`siglas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alumno` (
  `matricula` INT(7) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `grupo` VARCHAR(7) NULL,
  `carrera` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_Alumno_grupo1_idx` (`grupo` ASC),
  INDEX `fk_Alumno_carrera1_idx` (`carrera` ASC),
  CONSTRAINT `fk_Alumno_grupo1`
    FOREIGN KEY (`grupo`)
    REFERENCES `grupo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_carrera1`
    FOREIGN KEY (`carrera`)
    REFERENCES `carrera` (`siglas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad` (
  `id_actividad` INT(7) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id_actividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad` (
  `id_unidad` INT(7) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asistencia` (
  `id_asistencia` INT(7) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_entrada` TIME NOT NULL,
  `hora_salida` TIME NULL,
  `alumno` INT(7) NOT NULL,
  `actividad` INT(7) NOT NULL,
  `unidad` INT(7) NOT NULL,
  `nivel` INT(1) NULL,
  `teacher` VARCHAR(50) NULL,
  PRIMARY KEY (`id_asistencia`),
  INDEX `fk_asistencia_Alumno1_idx` (`alumno` ASC),
  INDEX `fk_asistencia_actividad1_idx` (`actividad` ASC),
  INDEX `fk_asistencia_unidad1_idx` (`unidad` ASC),
  CONSTRAINT `fk_asistencia_Alumno1`
    FOREIGN KEY (`alumno`)
    REFERENCES `alumno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencia_actividad1`
    FOREIGN KEY (`actividad`)
    REFERENCES `actividad` (`id_actividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asistencia_unidad1`
    FOREIGN KEY (`unidad`)
    REFERENCES `unidad` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
